name: Run Node Test
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20, 22, 24]
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
      - name: Run coverage report
        run: |
          # remove the first and last table lines
          npm run cov -- --no-color | sed '0,/^---/{//d}; $ d' | tee $GITHUB_STEP_SUMMARY
